[pytest]
minversion = 7.0
addopts = --cov=flask/src --cov-report term-missing
pythonpath = flask/src
testpaths = flask/tests
env =
    DEBUG=False
    POD_NAME=test-pod
    OS2_API_KEY=api-key
    OS2_APPLICATION_ID=app-id
    OS2_VERIFY=False
    OS2_DEVICE_PROFILE_ID=device-id
